import Link from "next/link";
import { ArrowRight, Check, FileSearch, MessageSquareText, ShieldCheck } from "lucide-react";
import { practiceAreas, studio } from "@/lib/content";
export default function Home() { return <main>
<section className="hero"><div className="eyebrow">ESTUDIO JURÍDICO · ARGENTINA</div><h1>Orientación jurídica clara, estratégica y cercana.</h1><p className="lead">Analizamos cada situación con seriedad, ordenamos la información inicial y facilitamos el contacto con el profesional adecuado.</p><div className="hero-actions"><a className="button primary" href="#consulta">Iniciar consulta guiada <ArrowRight/></a><Link className="button secondary" href="/contacto">Hablar con recepción</Link></div><p className="fine">La consulta guiada recopila información preliminar y no constituye asesoramiento jurídico.</p></section>
<section className="trust"><span><ShieldCheck/>Tratamiento responsable</span><span><FileSearch/>Revisión ordenada</span><span><MessageSquareText/>Atención humana</span></section>
<section id="estudio" className="split"><div><div className="eyebrow">NUESTRO ENFOQUE</div><h2>Criterio profesional desde el primer contacto</h2></div><div><p>Creemos que una buena orientación empieza por escuchar, identificar la información relevante y explicar con claridad los próximos pasos posibles.</p><p className="notice">{studio.notice}</p></div></section>
<section id="areas" className="section"><div className="section-heading"><div><div className="eyebrow">ÁREAS DE PRÁCTICA</div><h2>Una mirada integral</h2></div><p>Contenido demostrativo que deberá confirmarse antes del lanzamiento comercial.</p></div><div className="areas">{practiceAreas.map((area,index)=><article key={area.slug}><span>0{index+1}</span><h3>{area.name}</h3><p>{area.summary}</p><Link href={`/areas-de-practica/${area.slug}`}>Conocer más <ArrowRight size={16}/></Link></article>)}</div></section>
<section id="proceso" className="process section"><div><div className="eyebrow">CÓMO TRABAJAMOS</div><h2>Un proceso simple y transparente</h2></div><ol><li><span>1</span><div><h3>Contanos tu situación</h3><p>El asistente recopila la información inicial de forma guiada.</p></div></li><li><span>2</span><div><h3>Revisión interna</h3><p>Recepción ordena la consulta y la deriva al profesional adecuado.</p></div></li><li><span>3</span><div><h3>Contacto personal</h3><p>El equipo evalúa los próximos pasos sin prometer aceptación ni resultados.</p></div></li></ol></section>
<section id="consulta" className="cta"><div className="eyebrow">PRIMER PASO</div><h2>Empezá por ordenar tu consulta</h2><p>Respondé unas preguntas para que podamos comprender mejor tu situación.</p><div className="checks"><span><Check/>Tus respuestas quedan registradas</span><span><Check/>Podés cancelar en cualquier momento</span></div><p className="fine">Abrí el botón “Iniciar consulta guiada” para comenzar.</p></section>
<section className="faq section"><div><div className="eyebrow">PREGUNTAS FRECUENTES</div><h2>Antes de comenzar</h2></div><div><details><summary>¿El chatbot brinda asesoramiento?</summary><p>No. Recopila información preliminar para revisión humana.</p></details><details><summary>¿La consulta implica que aceptaron mi caso?</summary><p>No. El estudio debe evaluar primero la situación y posibles conflictos.</p></details><details><summary>¿Qué información conviene enviar?</summary><p>Una descripción breve y fechas relevantes. No envíes documentos o datos sensibles.</p></details></div></section>
</main>; }
